name: Translator - Create new Release

on:
  push:
    branches:
      - master
    paths:
      - 'plugins/Translator/**'
      - '!plugins/Translator/package.json'
      - '!plugins/Translator/CHANGELOG.md'
jobs:
  release:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: plugins/Translator
    
    steps:
      -
        uses: actions/checkout@v1
      -
        uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://registry.npmjs.org/
      -
        name: Installing parent npm modules
        run: cd ../../ && npm install
      -
        name: Installing npm modules
        run: npm install
      -
        name: Build library
        run: npm run build
      -
        name: Create Changelog and bump release version
        uses: labor-digital/conventional-release-action@master
        with:
          github-token: ${{ secrets.github_token }}
      -
        name: Publish library on npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
